baseURL = "https://<USERNAME>.github.io/<REPO>/"
title = "Allied Mechanical"
languageCode = "en-us"

[params]
  author = "<AUTHOR_NAME>"
  description = "<SITE_DESCRIPTION>"
  dateFormat = "Jan 2, 2006"
  themeColor = "#0d9488"
  logo = "images/logo.png" # placeholder path
  favicon = "images/favicon.ico" # placeholder path
  [params.social]
    twitter = "<TWITTER_URL>"
    facebook = "<FACEBOOK_URL>"
    linkedin = "<LINKEDIN_URL>"
  [params.analytics]
    googleAnalytics = "<GA_TRACKING_ID>"
  [params.seo]
    defaultImage = "images/default-og.jpg" # placeholder path
    keywords = ["construction", "HVAC", "mechanical"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "Services"
    url = "/services/"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"

[permalinks]
  blog = "/blog/:slug/"
  services = "/services/:slug/"

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[minify]
  disableXML = true
