name: CI

on:
  pull_request:
    paths:
      - 'index.html'
      - 'assets/**'
      - 'sw.js'
      - 'manifest.json'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HTML Validate
        run: npx html-validate "index.html"
      - name: Stylelint
        run: npx stylelint "assets/css/style.css"
      - name: ESLint
        run: npx eslint "assets/js/script.js"
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
