name: Lighthouse CI
on: [push]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build:css
      - run: npm install -g @lhci/cli htmlhint stylelint eslint
      - run: htmlhint index.html
      - run: stylelint styles.css
      - run: eslint --no-eslintrc main.js || true
      - run: lhci autorun --upload.target=temporary-public-storage || true
