name: Test Workflow Trigger

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Test workflow triggered successfully!"
